import arcpy

# Variables
rcl = "road_centerlines_test_2"
ssap = "ssap_test_data_2"

# Compound Selection - View roads within 500m of Madison County parcels owned by CA
arcpy.management.SelectLayerByAttribute('Madison_Parcels', 'NEW_SELECTION', "OwnerState= 'CA'")
arcpy.management.SelectLayerByLocation(rcl, 'WITHIN_A_DISTANCE', 'Madison_Parcels', 500, 'ADD_TO_SELECTION')

# Additional compound selection for roads within 500m of parcels owned by OR (auto generated by select by location tool)
arcpy.management.SelectLayerByAttribute("Madison_Parcels", "NEW_SELECTION", "OwnerState= 'OR'", None)
arcpy.management.SelectLayerByLocation("road_centerlines_test_2", "WITHIN_A_DISTANCE", "Madison_Parcels", "500 Meters", "NEW_SELECTION", "NOT_INVERT")

# Clearing Selections:
arcpy.management.SelectLayerByAttribute(ssap, 'CLEAR_SELECTION')
arcpy.management.SelectLayerByAttribute(rcl, 'CLEAR_SELECTION')

# For loops to clear all selections:
